### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by staycool13** [BlinkReceipt/blinkreceipt-js#14]
request url : https://sandbox.blinkreceipt.com/api_scan

site alert error message : BlinkReceipt error: Failed to scan image: Internal Server Error

returns : Internal Server Error 500

attaching sample receipt

![target-receipt-img1](https://user-images.githubusercontent.com/53722825/130184803-f6344bff-eac2-4386-9525-bf02af945cff.jpg)

**Comment by dpanzer** [comment]
Thanks for reporting, this should be resolved now
