### ISSUE TITLE
[Question] What are the differences between the item_confidence and the trip_confidence?

### ISSUE THREAD

**Issue by cxrod** [BlinkReceipt/blinkreceipt-js#7]
Hi,

I look the answer in the [Swagger API Docs](https://app.swaggerhub.com/apis-docs/blinkreceipt/apiscan/14#/default/post_api_scan_v14) but I hoping that you can give me a more detailed answer.

Regards

**Comment by dpanzer** [comment]
Hi @cxrod - `trip_confidence` is an indication of how confident we feel about "trip-level" data such as merchant, date, total, etc whereas `item_confidence` is an indication of how confident we feel about "item-level" data such as product description, product number, quantity, price, etc
